version: "3"
services:
  app:
    build: .
    container_name: app
    env_file:
      - app.env
    networks:
      - backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: rebuild
          path: ./requirements.txt
          target: /app/requirements.txt

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - backend
    volumes:
      - .\.redis_data:/data
    restart: always

  db:
    image: postgres:16.0-alpine
    container_name: postgres
    networks:
      - backend
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - .\.db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

networks:
  backend:

volumes:
  .db_data:
