version: "3.7"
services:
  app:
    build: .
    container_name: app
    networks:
      - backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image:
      postgres:16.0-alpine
    container_name: postgres
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - .\.db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:

volumes:
  .db_data:
